spring:
  datasource:
    url: jdbc:mysql://localhost:3306/savorai_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SavorAI
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  ai:
    openai:
      api-key: ${openai_api_key}
      chat:
        model: gpt-4o
        temperature: 1
        max-tokens: 2000
      image:
        options:
          model: dall-e-2
          quality: standard # DALL-E-2 only have standard
          width: 512
          height: 512
server:
  port: 8080
logging:
  level:
    root: info
    dev.idachev.backend: debug
    org.hibernate.SQL: debug
    org.springframework.web: debug
cors:
  allowed-origins: "http://localhost:5173"
cloudinary:
  cloud-name: ${cloudinary_cloud_name}
  api-key: ${cloudinary_api_key}
  api-secret: ${cloudinary_api_secret}
