spring:
  datasource:
    url: jdbc:mysql://localhost:3306/savorai_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SavorAI

server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug

openai:
  apiKey: ${openai_api_key}
  apiTimeout: 20
  baseUrl: https://api.openai.com/v1/chat/completions
  imageGenerationUrl: https://api.openai.com/v1/images/generations
  systemMessage: "You are a professional chef assistant. Generate a unique recipe for each request. Provide detailed step-by-step instructions and ensure the recipe is clear, creative, and complete."
  modelName: "gpt-4"
  maxTokens: 2000
  temperature: 1.0
  topP: 0.9
  choicesCount: 1
  imageCount: 1
  imageSize: "256x256"
