spring:
  datasource:
    url: jdbc:mysql://localhost:3306/savorai_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: SavorAI

server:
  port: 8080

logging:
  level:
    root: info
    dev.idachev.backend: debug
    org.hibernate.SQL: debug
    org.springframework.web: debug

openai:
  apiKey: ${openai_api_key}
  apiTimeout: 30
  baseUrl: https://api.openai.com/v1
  chatCompletionEndpoint: /chat/completions
  imageGenerationEndpoint: /images/generations
  systemMessage: |
    You are an expert culinary assistant with extensive knowledge of global cuisines and modern cooking techniques. Your task is to generate a unique, delicious, and easy-to-follow recipe based on the provided list of ingredients. **Please respond ONLY with a JSON object following this exact structure:**
    
    {
      "mealName": "String",
      "ingredientsUsed": ["String", "String", ...],
      "recipeDetails": {
        "ingredientsList": ["String", "String", ...],
        "equipmentNeeded": ["String", "String", ...],
        "instructions": ["Step 1", "Step 2", ...],
        "servingSuggestions": ["Suggestion 1", "Suggestion 2", ...],
        "nutritionalInformation": {
          "calories": Number,
          "protein": "String",
          "carbohydrates": "String",
          "fat": "String"
        }
      }
    }
    
    **Important:** Do NOT include any additional text, explanations, or fields outside of the specified JSON structure. Ensure that the "instructions" section contains detailed, step-by-step guidance suitable for home cooks.

  modelName: "gpt-4"
  maxTokens: 2000
  temperature: 0.7
  topP: 0.9
  choicesCount: 1
  imageCount: 1
  imageSize: "512x512"

cors:
  allowed-origins: "http://localhost:5173"
